@extends('layouts.site')
@section('title', 'Patient Feedback')
@section('heading', 'Share Your Experience')
@section('intro', 'Your feedback helps us strengthen patient care, communication and hospital services.')
@section('content')
@php
    $phone = $siteSettings['site_phone'] ?? '01662-245450';
    $email = $siteSettings['site_email'] ?? 'care@aarogyahospital.com';
    $address = $siteSettings['address'] ?? 'Opposite Vishwas School, Near LIC Office, Urban Estate II, Hisar, Haryana 125001';
    $departmentOptions = collect($departments ?? [])->filter()->values();
@endphp
<section class="inner-section feedback-page"><div class="wrap feedback-layout"><div class="feedback-copy"><span class="eyebrow">WE ARE LISTENING</span><h2>Every voice helps us care better.</h2><p>Tell us what worked well or where we can improve. Do not include sensitive clinical information in this public form.</p><div class="contact-tile"><i>☎</i><div><small>Need immediate assistance?</small><a href="tel:{{ preg_replace('/\D+/', '', $phone) }}"><strong>{{ $phone }}</strong></a></div></div><div class="feedback-contact-note"><a href="mailto:{{ $email }}">{{ $email }}</a><span>{{ $address }}</span></div></div><div class="feedback-card">@if(session('feedback_success'))<div class="form-success"><i>✓</i><h3>Thank you for your feedback.</h3><p>Your response has been recorded for our patient-care team.</p></div>@else @if($errors->any())<div class="form-error" role="alert">{{ $errors->first() }}</div>@endif<form method="post" action="{{ route('feedback.store') }}" class="feedback-form">@csrf<div class="rating-field"><span>Overall experience *</span><div class="rating-options">@foreach(range(1,5) as $rating)<label><input type="radio" name="rating" value="{{ $rating }}" @checked(old('rating') == $rating) required><span>{{ $rating }}<small>{{ $rating === 1 ? 'Poor' : ($rating === 5 ? 'Excellent' : '') }}</small></span></label>@endforeach</div></div><label><span>Your Name *</span><input name="name" value="{{ old('name') }}" required maxlength="80"></label><label><span>Mobile Number</span><input name="phone" type="tel" value="{{ old('phone') }}" maxlength="18"></label><label><span>Email</span><input name="email" type="email" value="{{ old('email') }}" maxlength="120"></label><label><span>Department visited</span><select name="department"><option value="">Select department</option>@foreach($departmentOptions as $department)<option @selected(old('department') === $department)>{{ $department }}</option>@endforeach<option @selected(old('department') === 'Other')>Other</option></select></label><label class="full"><span>Your feedback *</span><textarea name="message" required maxlength="1500" placeholder="Tell us about your experience…">{{ old('message') }}</textarea></label><button class="btn btn-primary full" type="submit">Submit Feedback →</button></form>@endif</div></div></section>
@endsection
